version: 2

workflows:
  version: 2
  simple-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

jobs:
  build:
    docker:
      - image: 'haskell:9.0'

    steps:
      - checkout
      - restore_cache:
          key: 'v1-websockets-{{ arch }}-{{ .Branch }}'
      - run:
          name: 'Install virtualenv for autobahn'
          command: 'apt-get update && apt-get install --yes virtualenv python2.7-dev'
      - run:
          name: 'Update package index'
          command: 'cabal update'
      - run:
          name: 'Build'
          command: 'cabal build --enable-tests -f Example all'
      - run:
          name: 'Test'
          command: 'cabal test'
      - run:
          name: 'Run autobahn tests'
          command: 'bash tests/autobahn/autobahn.sh'
      - save_cache:
          key: 'v1-websockets-{{ arch }}-{{ .Branch }}-{{ .Revision }}'
          paths:
            - '~/.virtualenvs'
            - 'dist-newstyle'
